# Learning Numpy

In [1]:
%%time
"hello"

CPU times: user 4 µs, sys: 1 µs, total: 5 µs
Wall time: 9.3 µs


'hello'

In [2]:
%pip install nptyping beartype --upgrade --force


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 847.7 kB/s eta 0:00:00 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 872.4/872.4 kB 4.4 MB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.0/18.0 MB 28.8 MB/s eta 0:00:0000:0100:01
Note: you may need to restart the kernel to use updated packages.


In [5]:
data = [[0, 1, 2, 3],
        [4, 5, 6, 7],
        [8, 9, 10, 11]]

a : np.ndarray = np.array(data) # object to store [1,2,3,4] = vector

display(f" object {a}") # prints
display(f"objec shape {a.shape}") # prints the shape of the object () = 0 -Denormalized
display(f" Object type {a.dtype}") # prints the dtype of the object
display(f"Object type with global function {type(a)}") # prints the dtype of the
display(f"Number of dimension {a.ndim}") # prints the number of dimensions
display(f"Total items in Array : {a.size}") # prints the size of the object
display(f"{a.itemsize}") # prints the itemsize of the object

NameError: name 'np' is not defined

In [9]:
%pip install numpy --upgrade --force

  Using cached numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
Using cached numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.0 MB)
  Attempting uninstall: numpy
    Found existing installation: numpy 1.26.4
    Uninstalling numpy-1.26.4:
      Successfully uninstalled numpy-1.26.4
Note: you may need to restart the kernel to use updated packages.


In [11]:
from nptyping import NDArray, Shape, UInt64
from typing import Any
import numpy as np

1. `np.arange(3*3)`: This uses NumPy's `arange` function to create a 1D array with values from 0 to 8 (exclusive), as `3*3` equals 9. The `arange` function generates a sequence of numbers based on the parameters provided, similar to Python's built-in `range` function.

2. `.reshape(3,3)`: This uses the `reshape` method to reshape the 1D array created by `arange` into a 3x3 2D array. The `reshape` method changes the shape of the array without changing its data, so the original array's elements are simply reorganized into the specified shape.

Putting it all together, `np.arange(3*3).reshape(3,3)` creates a 3x3 array containing values from 0 to 8, arranged in rows and columns.

In [14]:

a : NDArray[Shape["Size, Size"],Any] = np.arange(3*3).reshape(3,3)
print(a)
print("===================================")
# a : NDArray[Shape["Size, Size"],Any] = np.arange(5*3).reshape(5,3)
# print(a)


a : NDArray[Shape["Size, Size"],Any] = np.arange(3*3)
print(a)


[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2 3 4 5 6 7 8]


3*3 means 9 elements or 3 rows 3 column in 2d array

In [16]:
a : NDArray[Shape["Size, Size, Size"],Any] = np.arange(2*3*3).reshape(2,3,3)
print(a)
print(" 2 images with 3 rows and 3 columns")

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]
 2 images with 3 rows and 3 columns


In [17]:
a : NDArray[Shape["Size, Size, Size"],Any] = np.arange(2*3*3).reshape(2,3,3)
print(a)

print(" even numbers in the array")
a[a%2==0] 

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16])

In [19]:
# creating numpay array
np.asarray([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [25]:
# creating zeros array
np.zeros(10) 

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [29]:
# print("creating 3x3 zeros array")
# np.zeros((3,3))

print("creating 3x3 ones array")
np.ones((3,3))

creating 3x3 ones array


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])